name: Release Deno build

on: create

jobs:
  ci_cd:
    name: CI / CD
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
      - name: Installing Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Checking Deno
        run: deno --version
      - name: Caching dependencies
        run: deno cache index.ts
      - name: Running Deno
        run: deno run -A --unstable index.ts
      - name: Compiling for Linux
        run: deno compile --unstable --lite --target x86_64-unknown-linux-gnu   --allow-env --allow-net --allow-read --allow-run --allow-write --output build/jvms index.ts
      - name: Compiling for Windows
        run: deno compile --unstable --lite --target x86_64-pc-windows-msvc     --allow-env --allow-net --allow-read --allow-run --allow-write --output build/jvms.exe index.ts
      - name: Compiling for MacOS
        run: deno compile --unstable --lite --target x86_64-apple-darwin        --allow-env --allow-net --allow-read --allow-run --allow-write --output build/jvms.dmg index.ts
      - name: Generating sha256 checksums
        run: for f in build/* ; do sha256sum "$f" > "$f.sha256sum" ; done
      - name: Listing files
        run: ls -lR
      - name: Adding builds to GitHub releases tab
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
